### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [aihe/random-game#1]
Hello! @aihe 

I like to contribute to open source software. In my free time, I design a logo to support the open source community. I designed a logo for random-game. If you like it, i can update the readme file.

If there are any changes you want to make to logoda, please let me know. I will wait for feedback.

Have a nice day!

![randomgame](https://user-images.githubusercontent.com/36298335/45107323-e3583700-b141-11e8-89e6-abe624dde368.jpg)

**Comment by reallinfo** [comment]
Oh, you're welcome. No problem. How is this?

![2](https://user-images.githubusercontent.com/36298335/45114344-6df66180-b155-11e8-95d4-905a81330544.jpg)

**Comment by reallinfo** [comment]
okay, i will send necessary all files. Do you want to put a banner in the readme file like this?  it will look like this ;

![4](https://user-images.githubusercontent.com/36298335/45116946-f298ae00-b15c-11e8-94d2-911ab1943472.png)

**Comment by aihe** [comment]
Oh god, big yes that's perfect, thanks again!

**Comment by reallinfo** [comment]
I sent a pr. If there is a problem, feel free to say me.
